-- ============================================================
-- BuildSmart AI — ai_designs & ai_materials tables (Phase 4)
-- ============================================================
-- Supports the generate-ai-design Edge Function and the
-- aiDesignService. These tables store the AI-generated design
-- and material recommendations for each project.
-- IDEMPOTENT — safe to run multiple times.

BEGIN;

-- ai_designs: one row per AI-generated design per project.
CREATE TABLE IF NOT EXISTS public.ai_designs (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id      uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  customer_id     uuid NOT NULL,
  design_title    text NOT NULL,
  design_summary  text,
  style           text DEFAULT 'Modern',
  floors          integer,
  bedrooms        integer,
  bathrooms       integer,
  layout_recommendation  text,
  exterior_recommendation text,
  interior_recommendation text,
  sustainability_recommendation text,
  estimated_cost_min  numeric,
  estimated_cost_max  numeric,
  ai_response         text, -- raw JSON from Gemini
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ai_materials: material recommendations generated by the AI.
CREATE TABLE IF NOT EXISTS public.ai_materials (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id      uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  customer_id     uuid NOT NULL,
  material_name   text NOT NULL,
  category        text,
  quantity        text,
  estimated_cost  numeric,
  recommendation  text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Indexes for fast lookups by project.
CREATE INDEX IF NOT EXISTS idx_ai_designs_project   ON public.ai_designs(project_id);
CREATE INDEX IF NOT EXISTS idx_ai_materials_project ON public.ai_materials(project_id);

-- RLS: customers only see their own AI designs/materials.
ALTER TABLE public.ai_designs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_materials ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ai_designs_select_own" ON public.ai_designs;
CREATE POLICY "ai_designs_select_own"
  ON public.ai_designs FOR SELECT
  USING (auth.uid() = customer_id);

DROP POLICY IF EXISTS "ai_designs_insert_own" ON public.ai_designs;
CREATE POLICY "ai_designs_insert_own"
  ON public.ai_designs FOR INSERT
  WITH CHECK (auth.uid() = customer_id);

DROP POLICY IF EXISTS "ai_materials_select_own" ON public.ai_materials;
CREATE POLICY "ai_materials_select_own"
  ON public.ai_materials FOR SELECT
  USING (auth.uid() = customer_id);

DROP POLICY IF EXISTS "ai_materials_insert_own" ON public.ai_materials;
CREATE POLICY "ai_materials_insert_own"
  ON public.ai_materials FOR INSERT
  WITH CHECK (auth.uid() = customer_id);

-- Grants
GRANT SELECT, INSERT ON TABLE public.ai_designs TO authenticated;
GRANT SELECT, INSERT ON TABLE public.ai_materials TO authenticated;

COMMIT;